### ISSUE TITLE
Module discrepancy - probably just a copy/paste issue from the other module

### ISSUE THREAD

**Issue by nostradomus** [ADVANTICS/documentation#1]
![image](https://user-images.githubusercontent.com/27766555/166658891-0f83af3d-de0a-4e13-930a-1ab85354708c.png)

**Comment by JorgeSolaM** [comment]
This is fine. That is just an example of how the output of AFPU looks like, and is an image that I reuse in all power modules. No need to have the same image just changing the module type.
